- course: HackerRank
  institute: Per Scholas
  dates: Current
  logo: hacker_rank.png
  
- course: QwikLabs
  institute: Cisco
  dates: Fall 2020
  logo: qwiklabs.png
  
- course: ISC² CyberWarriors
  institute: ISC² CyberWarriors
  dates: 2019 - 2021
  logo: Hacker_Rank2.png
  
- course: Institute for Veterans and Military Families (IVMF)
  institute: Google IT Professional Certification
  dates: Fall 2019
  logo: fellowship.svg
